package com.dps.roboleague.domain.audit;

public enum AuditAction {
    SEASON_CREATED,
    COMPETITION_CREATED,
    RULEBOOK_PUBLISHED,
    TEAM_REGISTERED,
    TEAM_REJECTED,
    ROUND_SCHEDULED,
    RESULT_CAPTURED,
    RESULT_SOURCE_RECEIVED,
    RESULT_CORRECTED,
    STANDINGS_GENERATED,
    STANDINGS_PUBLISHED,
    STANDINGS_RECALCULATED,
    APPEAL_SUBMITTED,
    APPEAL_RESOLVED
}
